spring.application.name=gns

# Server Configuration
server.servlet.context-path=/api
server.port=8080

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.serialization.indent-output=true

# Active le profil dev par défaut (peut être surchargé avec spring.profiles.active=prod)
spring.profiles.active=dev

# JPA Common Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Jackson
# Removed incompatible properties - Jackson will use default settings



