spring.application.name=gns

# Server Configuration
server.servlet.context-path=/api
server.port=8080

# Jackson
spring.jackson.serialization.INDENT_OUTPUT=true

# Active le profil dev par défaut
spring.profiles.active=dev

# JPA Common Settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

cloudinary.cloud-name=djhq0lubk
cloudinary.api-key=233522294593757
cloudinary.api-secret=**********

CLOUDINARY_URL=cloudinary://233522294593757:**********@djhq0lubk

# Gemini Configuration
gemini.api-key=AIzaSyACyksWkgoZgTHjbDPAQSj9NOSHoivJtKY
gemini.model=gemini-2.0-flash

# Multipart
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
