package com.backend.gns.student.domain.enums;

public enum TypeParametreDbs {
  AGE_MAX_LICENCE,
  MONTANT_TRANCHE_STANDARD,
  MONTANT_TRANCHE_SUPERIEURE,
  L1_MOYENNE_MIN_PASSABLE,
  L1_MOYENNE_MIN_MENTION_SUP,
  L2_CREDITS_MIN_STANDARD,
  L2_CREDITS_MIN_SUPERIEUR,
  L3_CREDITS_MIN_STANDARD,
  L3_CREDITS_MIN_SUPERIEUR,
  L4_CREDITS_MIN_STANDARD,
  L5_CREDITS_MIN_STANDARD
}
